name: Auto Merge

on:
  workflow_dispatch:  # This allows manual trigger via API or GitHub UI
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: integer

jobs:
  automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      actions: write  # Added actions: write to ensure proper permissions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Check PR details
        uses: actions/github-script@v6
        with:
         script: |
           const pr_number = '${{ github.event.inputs.pr_number }}'; // Pass pr_number as a string from the context
           if (pr_number) {
              console.log(`PR number: ${pr_number}`);
           } else {
              console.log('PR number not found, this workflow might not have been triggered by a pull request event.');
           }
            
      - name: Ensure PR is mergeable
        id: mergeable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Default token provided by GitHub Actions
        run: |
          # Fetch PR details to check mergeability
          pr_details=$(gh pr view ${{ github.event.inputs.pr_number }} --json mergeable --jq .)
          echo "PR Details: $pr_details"
          mergeable=$(echo "$pr_details" | jq -r .mergeable)
          echo "Mergeable state: $mergeable"
          
          if [ "$mergeable" = "MERGEABLE" ]; then
            echo "Pull request is mergeable."
          elif [ "$mergeable" = "false" ]; then
            echo "Pull request is not mergeable."
            exit 1
          elif [ "$mergeable" = "null" ]; then
            echo "Mergeable state is unknown. Please check the PR status."
            exit 1
          else
            echo "Unexpected mergeable state: $mergeable"
            exit 1
          fi

      - name: Automerge Script
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: ${{ github.event.inputs.pr_number }}
            });
            
            // Check mergeable state in the PR data (mergeable is a boolean)
            if (pr.mergeable_state === "dirty") {
              console.log("Pull request has merge conflicts.");
              return;
            }
            if (pr.mergeable_state === "clean") {
              console.log("PR is clean and ready for merging.");
            } else {
              console.log("Mergeable state:", pr.mergeable_state);
            }
