name: CI Workflow
 
on:
  pull_request_review:
    types:
      - submitted  # Trigger when a review is submitted (approved or changes requested)
jobs:
  build:
    runs-on: ubuntu-latest
 
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: SetUp Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
 
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            python -m pip install pytest
 
      - name: Run tests
        run: pytest
        
      - name: Run Python program
        run: python main.py

      - name: Step in Python CI
        run: echo "Running Python CI"
     
