name: Python Check Workflow

on:
  pull_request_target:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked

  pull_request_review:
    types:
      - submitted  # Trigger when a review is submitted (approved or changes requested)
      
    paths:
      - '**/*.py'
      - '.github/workflows/*'
      - 'checks.yml'
      - 'main.yml'

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pyflakes

    - name: Run Python checks
      run: |
        python doc1.py
