name: Build
on:
  workflow_run:
    workflows: ["Main Workflow"]
    types:
      - completed
  workflow_dispatch:  # Allows manual trigger via GitHub UI or API (optional)
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: integer

jobs:
  build:
    runs-on: ${{matrix.os}}
 
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SetUp Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'
 
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
 
      - name: Run tests
        run: pytest

  trigger_automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Debug GitHub Context (to check variables)
        run: |
          echo "head_ref: ${{ github.head_ref }}"
          echo "ref: ${{ github.ref }}"
          echo "PR source branch: ${{ github.event.pull_request.head.ref }}"
          
      
      - name: Trigger Automerge Workflow using GitHub API
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/automerge.yml/dispatches \
          -d '{
                "ref": "refs/heads/${{ github.event.pull_request.head.ref }}", 
                "inputs": {
                  "pr_number": "${{ github.event.pull_request.number }}"
                }
              }'
